[package]
name = "rust-releases"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
comfy-table = "7.1.1"
semver = "1.0.23"